### PR TITLE
Print an error message if no target node is defined

### PR DESCRIPTION
**Pull request by Calinou**
This also removes trailing whitespace.

### CODE REVIEW

**Comment by Calinou** [comment]
Bump :slightly_smiling_face:

**Comment by lawnjelly** [comment]
Oh wow! So sorry @Calinou, these didn't even appear in my github alerts for some reason?? I'll try and look through them, and figure out why my alerts aren't working! :scream:

**Comment by Calinou** [comment]
It's OK, no problem at all :slightly_smiling_face:

When you get a new issue or pull request on a repository you watch, you won't be considered as participating unless you were mentioned in OP. I guess I should start mentioning repository owners when making PRs like these :slightly_smiling_face:

**Comment by lawnjelly** [comment]
I think I had turned off 'watch' on it, maybe I was trying to figure out what watch did as I was new to github! I think that was the problem, all my fault! :blush: I've made sure to turn it on for all my repositories now.

**Comment by Calinou** [comment]
Also, we may want to change this for an `assert()` so the game stops when running it from the editor, like this: `assert(_m_Target != null, "A target must be defined for the Smoothing node to work.")`

Custom `assert()` messages are supported since Godot 3.2.

**Comment by lawnjelly** [comment]
Yup feel free to do another PR if you think that will work better! :grinning:

**Comment by Calinou** [comment]
PR opened: #4

**Pull request merged**
